// Generated by CoffeeScript 1.9.1
(function () {
    "use strict";
    module.exports = function (grunt) {
        grunt.loadNpmTasks("grunt-bower");
        grunt.loadNpmTasks("grunt-contrib-connect");
        grunt.loadNpmTasks("grunt-contrib-copy");
        grunt.loadNpmTasks("grunt-contrib-watch");
        grunt.loadNpmTasks('grunt-git-deploy');
        grunt.loadNpmTasks("grunt-exec");
        grunt.loadNpmTasks('grunt-browserify');
        grunt.initConfig({
            bower: {
                dev: {
                    dest: '_includes/vendor/',
                    js_dest: '_includes/vendor/js/',
                    css_dest: '_includes/vendor/css/',
                    fonts_dest: '_includes/vendor/fonts/', //covers font types ['svg','eot', 'ttf', 'woff', 'woff2', 'otf']
                    png_dest: 'images/', // Images for Leaflet
                    options: {
                        keepExpandedHierarchy: false
                    }
                }
            },
            browserify: {
                main: {
                    src: 'js/map_source.js',
                    dest: 'js/map_bundle.js',
                }
            },
            exec: {
                jekyll_dev: {
                    cmd: "jekyll build --trace --config _config.yml,_config-dev.yml",
                },
                jekyll: {
                    cmd: "jekyll build --trace",
                }
            },
            watch: {
                options: {
                    livereload: true
                },
                source: {
                    files: ["_drafts/**/*", "_includes/**/*", "_layouts/**/*", "_posts/**/*", "css/**/*", "js/**/*", "_config.yml", "*.html", "*.md"],
                    tasks: ["browserify", "exec:jekyll_dev"]
                }
            },
            connect: {
                server: {
                    options: {
                        port: 4000,
                        base: '_site',
                        livereload: true
                    }
                }
            },
            git_deploy: {
                timstallmann: {
                    options: {
                        url: 'git@github.com:savaslabs/durham-restaurants-map.git',
                        branch: 'gh-pages'
                    },
                    src: '_site/'
                }
            }
        });
        grunt.registerTask("build", ["bower", "browserify", "exec:jekyll_dev"]);
        grunt.registerTask("serve", ["build", "connect:server", "watch"]);
        grunt.registerTask("deploy", ["bower", "browserify", "exec:jekyll", "git_deploy"]);
        return grunt.registerTask("default", ["serve"]);
    };

}).call(this);
